file_format: "1"
id: corne_cirque
name: Corne_cirque
type: shield
url: https://github.com/foostan/crkbd/
requires: 
  - pro_micro
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - corne_cirque_left
  - corne_cirque_right
